### ISSUE TITLE
Compare: how to remove a layer?

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#131]
Close does not remove a layer; add a remove option?

**Comment by danrademacher** [comment]
There's an X to remove a layer:
![image](https://cloud.githubusercontent.com/assets/1423200/6494233/0fafe600-c275-11e4-88db-8c791480d17b.png)

It doesn't appear till you stop loading, but clicking the loading spinner stops loading, then the X appears and you can remove the layer by clicking the X.

I just tested and it seems to work. If you have a different experience, go ahead and reopen this ticket with more info (browser, example queries, what happens when you click, etc.)
