### ISSUE TITLE
Quick clarification on the build process

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#137]
@standardpixel At the risk of me being annoying, I just wanted to clarify the build process again. Do you suggest to pull from the build branch or should I run my own build scripts (which is not a problem).

Falk

**Comment by danrademacher** [comment]
@postfalk, @standardpixel has the day off today. In theory, either method should work. In practice, it seems like best road would be to make sure you can run the build scripts per Eric's documentation, so that as the project evolves, you can easily deploy changes.

Also, did you see this comment, https://github.com/stamen/ecoengine/issues/129#issuecomment-78617601? Building for Holos integration is an option there, which I assume you want to use. I am not sure if the build branch on Github has that "turned on" or not.

**Comment by postfalk** [comment]
Ok Thanks
